coverage_service: cobertura_xml
xcodeproj: Skeleton.xcodeproj
workspace: Skeleton.xcworkspace
scheme: Skeleton
input_format: profdata
output_directory: Coverage/
build_directory: build/Build/
ignore:
  - SkeletonTests/*