name: Build and Test
on:
  push:
    branches:
    - master
    - develop
jobs:
  tests:
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
        - destination: 'platform=iOS Simulator,name=iPhone 11'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Dependencies
      run: |
        brew install sonar-scanner
        brew install swiftlint
        bundle install

    - name: SwiftLint
      run: |
        fastlane run swiftlint output_file:"./reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"

    - name: Run Build
      run: |
        set -o pipefail
        xcodebuild build-for-testing \
        -workspace SkeletonApp.xcworkspace \
        -scheme Skeleton \
        -destination 'platform=iOS Simulator,name=iPhone 11' \
        -derivedDataPath build \
        | xcpretty

    - name: Run Test
      run: |
        set -o pipefail
        xcodebuild test-without-building \
        -workspace SkeletonApp.xcworkspace \
        -scheme Skeleton \
        -destination 'platform=iOS Simulator,name=iPhone 11' \
        -derivedDataPath build \
        -enableCodeCoverage YES \
        | xcpretty
        
    - name: Run Slather
      env:
        workspace: 'SkeletonApp.xcworkspacej'
        params: '--build-directory ./DerivedData
        --output-directory ./reports
        --scheme Skeleton
        --binary-basename Skeleton'
      run: |
        slather coverage --sonarqube-xml ${params} ${workspace}
        slather coverage --cobertura-xml ${params} ${workspace}
         
    - name: Run SwiftLint
      run: |
        fastlane run swiftlint output_file:"./reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"
        
    - name: Run Sonar
      run: |
        sonar-scanner -X -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./reports/cobertura.xml
                
