name: Build and Test

on:
  push:
    branches:
    - master
    - develop

jobs:
  
  tests:
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
        - destination: 'name=iPhone 8'
          scheme: Skeleton
          xcode: latest
    steps:
    - uses: actions/checkout@v2
                      
    - name: Build and test
      run: |
        xcodebuild build test -workspace SkeletonApp.xcworkspace -scheme "${scheme}" -destination "${destination}" ${params} | xcpretty && exit ${PIPESTATUS[0]}
      env:
        project: 'Skeleton.xcodeproj'
        params: '-derivedDataPath ./DerivedData -enableCodeCoverage YES'
        scheme: ${{ matrix.scheme }}
        destination: ${{ matrix.destination }}
        DEVELOPER_DIR: ${{ matrix.xcode }}
        
  sonar:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Dependencies
      run: |
        # brew install java
        brew install sonar-scanner
        # brew install swiftlint
        gem install slather
              
    - name: Build and test
      run: |
        xcodebuild build test -workspace SkeletonApp.xcworkspace -scheme "${scheme}" -destination "${destination}" ${params} | xcpretty && exit ${PIPESTATUS[0]}
      env:
        project: 'Skeleton.xcodeproj'
        params: '-derivedDataPath ./DerivedData -enableCodeCoverage YES'
        scheme: Skeleton
        destination: 'name=iPhone 11'
                
    - name: Slather
      run: |
        slather coverage --sonarqube-xml ${params} ${project}
        slather coverage --cobertura-xml ${params} ${project}
      env:
        project: 'Skeleton.xcodeproj'
        params: '--build-directory ./DerivedData
        --output-directory ./reports
        --scheme Skeleton
        --binary-basename Skeleton'
         
    - name: SwiftLint
      run: |
        fastlane run swiftlint output_file:"./reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"
        
    - name: Run Sonar
      run: |
        sonar-scanner -X -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Code coverage
      if: github.ref == 'refs/heads/develop'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./reports/cobertura.xml


                
