name: Run CI 
on: [push, pull_request]

jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Gems
      run: |
        gem install bundler
        bundle install
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest-stable

    - name: Build
      run: |
        set -o pipefail
        slather setup
        xcodebuild build-for-testing \
        -workspace SkeletonApp.xcworkspace \
        -scheme Skeleton \
        -destination 'platform=iOS Simulator,name=iPhone 11' \
        -derivedDataPath build \
        | xcpretty
        
    - name: Archive derived data artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  test:
    name: Test Project
    needs: build
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest-stable

    - name: Download derived data artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Test
      run: |
        set -o pipefail
        xcodebuild test-without-building \
        -workspace SkeletonApp.xcworkspace \
        -scheme Skeleton \
        -destination 'platform=iOS Simulator,name=iPhone 11' \
        -derivedDataPath build \
        -enableCodeCoverage YES \
        | xcpretty
        
    - name: Coverage report
      run: slather coverage -x --binary-basename 'Skeleton'

    - name: Post coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./Coverage/cobertura.xml
        fail_ci_if_error: true
