name: CI      
on:
  push:
    branches:
    - master
    - develop
    - release/*
jobs:
  setup:
    name: Install dependencies
    runs-on: macOS-latest
    steps:       
      - name: Install Lint
        run: |
          set -o pipefail && brew install swiftlint
      - name: Install Carthage
        run: |
          set -o pipefail && brew install carthage
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Carthage
        run: |
          set -o pipefail && carthage update --platform iOS --no-use-binaries
  build:
    name: Run Build
    needs: setup
    runs-on: macOS-latest
    strategy:
         matrix:
           destination: ['platform=iOS Simulator,OS=latest,name=iPhone Xʀ']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        env: 
          CODECOV_TOKEN: "ff30730f-ba71-4122-a5c8-faf3dbcdfa57"
          destination: ${{ matrix.destination }}
        run: |
          set -o pipefail && xcodebuild clean build -scheme Skeleton -destination "${destination}" | xcpretty
  test:
    name: Run Test
    needs: [setup, build]
    runs-on: macOS-latest
    strategy:
         matrix:
           destination: ['platform=iOS Simulator,OS=latest,name=iPhone Xʀ']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        env: 
         destination: ${{ matrix.destination }}
        run: |
          set -o pipefail && xcodebuild test -scheme Skeleton -destination "${destination}" -enableCodeCoverage YES | xcpretty
