name: CI      
on: #pull_request
  push:
    branches:
    - master
    - develop
    - release/*
jobs:
  test:
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone XR']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Clean, Build and Test
        run: |
          set -o pipefail && xcodebuild clean build test -project Skeleton.xcodeproj -scheme Skeleton -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
